name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        include:
          - goos: windows
            ext: .exe
          - goos: linux
            ext: ""
          - goos: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Get release tag (e.g. v1.0.0)
        id: tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and Zip
        run: |
          mkdir -p bin
          BIN_NAME="divo-${RELEASE_TAG}-${{ matrix.goos }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o bin/divo${{ matrix.ext }} ./cmd/divo
          cd bin
          zip -r "${BIN_NAME}.zip" "divo${{ matrix.ext }}"
          cd ..

      - name: Upload zipped binary
        uses: actions/upload-artifact@v4
        with:
          name: divo-${{ matrix.goos }}
          path: bin/divo-${{ env.RELEASE_TAG }}-${{ matrix.goos }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true
          extract: false

      - name: Generate checksums
        run: |
          cd bin
          sha256sum *.zip > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/*.zip
            bin/checksums.txt
