name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Build binary into ./bin
        run: |
          mkdir -p bin
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
            -o bin/divo-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./cmd/divo

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: divo-binaries
          path: bin/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: divo-binaries
          path: bin

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
